# Generated by Django 4.2.20 on 2025-04-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_alter_section_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
