# Generated by Django 4.2.20 on 2025-04-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_alter_section_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
