# Generated by Django 4.2.20 on 2025-04-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_alter_section_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='construction.wallprofile'),
        ),
    ]
