# Generated by Django 4.2.20 on 2025-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_alter_section_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='assigned_team',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
